config/routes.rb
Rails.application.routes.draw do
  get 'bos/show'
  resource :bos 
  resource :product_sheets

end

app/models/bos.rb
class Bos < ActiveRecord::Base
end

app/models/product_sheet.rb
class ProductSheet < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bos_controller.rb
class BosController < ApplicationController
  def show
    @bos = Bos.all
  end
  def new
    @bos = Bos.new
  end
end

app/controllers/product_sheets_controller.rb
class ProductSheetsController < ApplicationController
  def show
    @product = ProductSheet.all
  end
  def new
    @product = ProductSheet.new
  end 
  def create
    @product = ProductSheet.new(person_params)
    @product.save
    redirect_to product_sheets_path
  end 
  private
  def person_params
    params.require(:product_sheet).permit(:product_name , :product_price, :product_number , :product_remark) 
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bos_helper.rb
module BosHelper
end

app/helpers/product_sheet_helper.rb
module ProductSheetHelper
end

app/views/bos/new.html.erb
<h1>Create New Bill Sheet</h1>

app/views/bos/show.html.erb
<h1>Bill Of Sale</h1>
<%= link_to "Create new Bill" , new_bos_path%>
<table>
  <tr>
    <td>Date</td>
    <td>Sale Number</td>
    <td>Product Name</td>
    <td>Price of Item</td>
    <td>Product Discount</td>
    <td>Quantity</td>
    <td>Product Amounts</td>
    <td>Charge</td>
  </tr>
  <% @bos.each do |sheet|%>
    <tr>
      <td><%= sheet.created_at%></td>
      <td><%= sheet.bos_number%></td>
      <td>product_name</td>
      <td>price_of_item</td>
      <td><%= sheet.bos_discount%></td>
      <td><%= sheet.bos_quantity%></td>
      <td><%= sheet.bos_price%></td>
      <td><%= sheet.bos_charge%></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sunlightdata</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href = "/js/bootstrap/css/bootstrap-themes.css">
  <link rel="stylesheet" href = "/js/bootstrap/css/bootstrap.min.css">
  <script src = "/js/bootstrap/js/bootstrap.min.js" ></script>
</head>
<body>
<ul class="nav nav-pils nav-justified" role="tablist">
  <li class = "active">
    <%= link_to "Prodcut Sheet" , product_sheets_path%>
  </li>
  <li>
    <%= link_to "Bill Of Sale" , bos_path%>
  </li>
</ul>
<%= yield %>

</body>
</html>

app/views/product_sheets/new.html.erb
<h1>Edit New Prodcut</h1>
<table>
  <%= form_for @product do |product|%>
    <tr>
      <td><span>Product Number</span></td>
      <td><%= product.text_field :product_number%></td>     
    </tr>
    <tr>
      <td>Product Name</td>
      <td><%= product.text_field :product_name%></td>
    </tr>
    <tr>
      <td>Product_price</td>
      <td><%= product.text_field :product_price%></td>
    </tr>
    <tr>  
      <td>Product Remark</td>
      <td><%= product.text_area :product_remark%></td>
    </tr>
        <%= product.submit :submit%>
        <%= button_tag "Reset", type: :reset %>
    <%end%>
        <%= link_to "Back" , product_sheets_path , method: "get" %>
</table>

app/views/product_sheets/show.html.erb
<link rel="stylesheet" href = "/css/sheet_style.css">
<div class = "content_bg">
  <div class = "content_title">
    <title>Product Sheet</title>
    <h1>Product Sheet</h1>
  </div>
  <span><%= link_to 'Edit New Product' , new_product_sheets_path%></span>
  <div class = "content">
    <table>
      <tr class = "title">
        <td>Prdouct Number</td>
        <td>Product Name</td>
        <td>Product Price</td>
        <td>Prdocut Remark</td>
      </tr>
      <% @product.each do  |sheet|%>
        <tr class = 'contnet'>
          <td><%= sheet.product_number %></td>
          <td><%= sheet.product_name %></td>
          <td><%= sheet.product_price%></td>
          <td><%= sheet.product_remark%></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>